### ISSUE TITLE
Your project is quite popular in our manufacturing service, would you like to sell it?

### ISSUE THREAD

**Issue by Libermentix** [xyzz/gamecard-microsd#11]
We have noticed that your open source project has been ordered with us quite frequently. Would you be interested in publishing it through [AISLER](https://aisler.net )? There are no costs involved for you, determine your margin and we'll take care of the rest. We only manufacture in Germany and would be happy to support you that way!

**Comment by xyzz** [comment]
Thanks for your offer and it's great to hear the adapter's getting more popular. As I understand, though, this would increase the price for people ordering through my affiliate link (something like that?). With this project I'm not seeking profit and would rather have people order it for cheaper.
