### ISSUE TITLE
Incorrect free memory reported when formatting a high capacity sd with default cluster size

### ISSUE THREAD

**Issue by Shinigati** [xyzz/gamecard-microsd#14]
So i'm not entirely sure if this problem is directly related to the plugin or if it's something more focused on the way the vita handles memory cards so i apologise if it's the latter.

but when i formatted my 256gb micro sd card with the default cluster size my vita would always report incorrect free space while windows and all other devices display it just fine but this only happens if the card was filled up by more than about 100gb of data that was tested, and what's more is after a while if i don't do much the free space it claims is still available starts to quickly disappear.

I have flashed zzblank.img, formatted and copied all the files back over twice and the problem still persisted, but finally after talking with a lot of people trying to figure it out i finally found the solution, the free space will only be 100% accurate if when formatting you choose 32kb cluster instead of the default option which in my case was 256kb.

**Comment by Shinigati** [comment]
So just a little update on this but some people have reported that one workaround is to format the sd card as Fat32 using the default cluster size which seems to run fine, i have also managed to get 64kb cluster with exFat working as well while 128kb gave the same issue so there definitely appears to be some compatibility issues i just have no idea why.

**Comment by CelesteBlue-dev** [comment]
What is your microSD default cluster size ?

**Comment by Shinigati** [comment]
I'm now using 64kb and there is no issue at all, before however i believe windows was defaulting it to 256kb, i also made a post on reddit about it and helped a few people by getting them to format using the correct size.

**Comment by CelesteBlue-dev** [comment]
Yes, readme should be updated telling that >64kB clusters don't work, and this issue should be closed.

**Comment by Shinygati** [comment]
> Yes, readme should be updated telling that >64kB clusters don't work, and this issue should be closed.

I didn't realise this issue was still open but i'm sure everyone knows by now how to correctly format their sd cards.
