### ISSUE TITLE
Sd Connector

### ISSUE THREAD

**Issue by DavisDev** [xyzz/gamecard-microsd#2]
Hello Xyzz!, 
What is the sd connector model?
Maybe some "serial number" component?
Greetings.

**Comment by xyzz** [comment]
I don't know the model number/name. Here's the purchasing guide though.

![sockets](https://user-images.githubusercontent.com/1065521/27766358-fc9190fa-5ed5-11e7-81ee-d026203ae2ef.jpg)

**Comment by DavisDev** [comment]
Thanks for answering!
And thanks for all your hard work!

**Comment by CrazyMaggot** [comment]
Good afternoon!
Will this work?
![image](https://user-images.githubusercontent.com/29947556/27908733-f5e38e24-6255-11e7-8d7b-e6cf3ce92d37.png)

https://www.chipdip.ru/product0/8492206932

**Comment by xyzz** [comment]
I think it should work.
