### ISSUE TITLE
Couple of problems on 3.65

### ISSUE THREAD

**Issue by superduperdrew12345** [xyzz/gamecard-microsd#24]
On the newest version compatible with 3.65 enso the memory card is no longer mounted to Uma0. Vitanshell still recognizes it as there and in the previous version it worked as expected. Additionally, I'm having trouble installing nonpdrm games on the sd adapter. When I refresh the livearea it says 0 refreshed but if I move the same files to my sd and then comment out gamesd from config.txt then it installs properly on the memory card. Existing nonpdrm games work still so it seems to be a problem with gamesd not allowing the new folder to be picked up.

**Comment by xyzz** [comment]
The memory card was never mounted to uma0 with this plugin. I've no idea about nonpdrm I don't use it, try asking its author.
