### ISSUE TITLE
Error opening board files in Eagle.

### ISSUE THREAD

**Issue by a7mag3ddon** [xyzz/gamecard-microsd#9]
Hi,

When i try and open either of the board design files i get this error..

> Loading Z:/adapter.brd ...
> 
> Error:
> 
> line 8, column 16: This is not an EAGLE file.

**Comment by xyzz** [comment]
I double-checked and it is in fact an EAGLE file, which opens fine, so there must be something wrong on your side.

**Comment by a7mag3ddon** [comment]
I just downloaded the trial version of AutoDesk Eagle from here > https://www.autodesk.com/products/eagle/free-download

Version 8.2.2 english

What can you suggest i open the files with instead?

**Comment by a7mag3ddon** [comment]
What version of eagle are you using ??

**Comment by xyzz** [comment]
I use eagle 8.2.1.
